### ISSUE TITLE
`requires-python` field does not conform to the spec

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-pep621#16]
`requires-python` maps to the [`Requires-Python` core metadata field](https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python), which follows the [PEP 440 specifier](https://peps.python.org/pep-0440/#version-specifiers) format, which allows multiple comma separated clauses.

We currently only allow one clause in our validation, which is wrong.

First reported in https://github.com/scipy/scipy/pull/16353#issuecomment-1146685941

**Comment by tylerjereddy** [comment]
I still need to deal with some blocking issues, so sounds like you'll resolve this matter first. Ideally the first release candidate would already be out, but things are rarely that simple anymore. Anyway, good that we can likely deal with this without too much trouble.
