### ISSUE TITLE
Do not consider `version` dynamic when writing RFC 822 metadata if it is set

### ISSUE THREAD

**Issue by FFY00** [FFY00/python-pep621#5]
We allow users to change the version attribute, but we still error out when generating RFC 822 metadata if it is set as dynamic. This should be allowed, if `version` (https://github.com/FFY00/python-pep621/blob/ed6aecfff8b8102236616a783dc2695f7e4afb14/pep621.py#L178) is set, we should not error out.

https://github.com/FFY00/python-pep621/blob/ed6aecfff8b8102236616a783dc2695f7e4afb14/pep621.py#L285-L288

**Comment by FFY00** [comment]
Actually, we can just remove it from that list, as we are already requiring it above.

https://github.com/FFY00/python-pep621/blob/ed6aecfff8b8102236616a783dc2695f7e4afb14/pep621.py#L249-L250

**Comment by pratham-bhatnagar** [comment]
hey @FFY00 can I work on this issue?
